{"level":"ERROR","timestamp":"2025-08-26T14:46:15.214563","namespace":"mcp_agent.mcp.mcp_agent_client_session","message":"send_request failed: Connection closed"}
{"level":"ERROR","timestamp":"2025-08-26T14:46:15.217526","namespace":"mcp_agent.mcp.mcp_connection_manager","message":"git: Lifecycle task encountered an error: unhandled errors in a TaskGroup (1 sub-exception)","data":{"exc_info":true,"data":{"progress_action":"Error","server_name":"git"}}}
{"level":"ERROR","timestamp":"2025-08-26T15:26:13.257804","namespace":"mcp_agent.mcp.mcp_agent_client_session","message":"send_request failed: Connection closed"}
{"level":"ERROR","timestamp":"2025-08-26T15:26:13.260052","namespace":"mcp_agent.mcp.mcp_connection_manager","message":"git: Lifecycle task encountered an error: unhandled errors in a TaskGroup (1 sub-exception)","data":{"exc_info":true,"data":{"progress_action":"Error","server_name":"git"}}}
{"level":"ERROR","timestamp":"2025-08-26T15:30:34.433444","namespace":"mcp_agent.mcp.mcp_agent_client_session","message":"send_request failed: Connection closed"}
{"level":"ERROR","timestamp":"2025-08-26T15:30:34.435972","namespace":"mcp_agent.mcp.mcp_connection_manager","message":"git: Lifecycle task encountered an error: unhandled errors in a TaskGroup (1 sub-exception)","data":{"exc_info":true,"data":{"progress_action":"Error","server_name":"git"}}}
{"level":"ERROR","timestamp":"2025-08-26T15:32:32.380329","namespace":"mcp_agent.mcp.mcp_agent_client_session","message":"send_request failed: Connection closed"}
{"level":"ERROR","timestamp":"2025-08-26T15:32:32.382984","namespace":"mcp_agent.mcp.mcp_connection_manager","message":"git: Lifecycle task encountered an error: unhandled errors in a TaskGroup (1 sub-exception)","data":{"exc_info":true,"data":{"progress_action":"Error","server_name":"git"}}}
{"level":"ERROR","timestamp":"2025-08-26T17:00:54.900448","namespace":"mcp_agent.mcp.mcp_connection_manager","message":"time: Lifecycle task encountered an error: 1 validation error for StdioServerParameters\ncommand\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type","data":{"exc_info":true,"data":{"progress_action":"Error","server_name":"time"}}}
